- job:
    name: "update-base-images"
    description: "update-base-images"
    defaults: global
    properties:
      - build-discarder:
          num-to-keep: 30
    node: vexxhost
    triggers:
      - timed: 'H H(2-5) 10 * *'
    parameters:
      - choice:
          name: IMAGE_TYPE
          choices:
            - ALL
            - CENTOS7
            - CENTOS8
            - RHEL7
            - RHEL8
            - UBUNTU18
            - RHCOS45
          description: "Image type for update or ALL(default)"
    scm:
      - tf-jenkins
    wrappers:
      - workspace-cleanup:
          disable-deferred-wipeout: true
      - timestamps
      - credentials-binding:
          - text:
              credential-id: VEXX_OS_USERNAME
              variable: OS_USERNAME
          - text:
              credential-id: VEXX_OS_PROJECT_NAME
              variable: OS_PROJECT_NAME
          - text:
              credential-id: VEXX_OS_PASSWORD
              variable: OS_PASSWORD
          - text:
              credential-id: VEXX_OS_DOMAIN_NAME
              variable: OS_USER_DOMAIN_NAME
          - text:
              credential-id: VEXX_OS_DOMAIN_NAME
              variable: OS_PROJECT_DOMAIN_NAME
          - text:
              credential-id: VEXX_OS_AUTH_URL
              variable: OS_AUTH_URL
    builders:
      - shell: |
          echo "DESCRIPTION Image type=$IMAGE_TYPE"
      - description-setter:
          regexp: "DESCRIPTION (.*)"
      - shell: |
          ./src/baukin/tf-jenkins/infra/vexxhost/update_base_images.sh
