- job:
    name: 'update-jenkins-jobs'
    description: "Updates jenkins jobs"
    defaults: global
    properties:
      - build-discarder:
          num-to-keep: 30
    node: master
    wrappers:
        - workspace-cleanup:
            disable-deferred-wipeout: true
        - credentials-binding:
          - username-password-separated:
              credential-id: self-jenkins
              username: USER
              password: PASSWORD
    scm:
      - tf-jenkins
    builders:
      - shell: |
          #!/bin/bash -e
          cd ./src/tungstenfabric/tf-jenkins/jjb
          python3 -m venv .venv
          source .venv/bin/activate
          pip3 install setuptools wheel --upgrade
          pip3 install jenkins-job-builder 
          echo "--------------------------------------------------------------------- test"
          make test
          echo "--------------------------------------------------------------------- update"
          echo "Creds $USER:$PASSWORD"
          make update
