---

# just build projects
- project:
    names:
      - tungstenfabric/tf-deployers-containers
      - tungstenfabric/tf-openshift-ansible
      - tungstenfabric/tf-dpdk
      - tungstenfabric/tf-java-api
      - tungstenfabric/tf-vijava
      - tungstenfabric/tf-vrouter-java-api
      - tungstenfabric/tf-vro-plugin
      - tungstenfabric/tf-vcenter-plugin
    check:
      templates:
        - build-centos
        - cleanup
    gate:
      templates:
        - build-centos
        - cleanup

# simple checks - no ubi
- project:
    names:
      - tungstenfabric/tf-vnc
      - tungstenfabric/tf-test
      - tungstenfabric/tf-dev-test
      - tungstenfabric/tf-third-party-packages
      - tungstenfabric/tf-nova-vif-driver
      - tungstenfabric/tf-heat-plugin
    check:
      templates:
        - ansible-os
        - cleanup
    gate:
      templates:
        - juju-k8s
        - ansible-os
        - cleanup

# simple checks with ubi in gating
- project:
    names:
      - tungstenfabric/tf-packages
      - tungstenfabric/tf-third-party
    check:
      templates:
        - ansible-os
        - cleanup
    gate:
      templates:
        - build-ubi
        - build-centos
        - juju-k8s
        - ansible-os
        - cleanup

# core TF projects with old style UT
- project:
    names:
      - tungstenfabric/tf-controller
      - tungstenfabric/tf-api-client
      - tungstenfabric/tf-common
      - tungstenfabric/tf-analytics
      - tungstenfabric/tf-neutron-plugin
      - tungstenfabric/tf-build
    check:
      templates:
        - test-unit
        - ansible-os
        - cleanup
    gate:
      templates:
        - test-unit
        - juju-k8s
        - ansible-os
        - cleanup

# old web UI projects
- project:
    names:
      - tungstenfabric/tf-web-core
      - tungstenfabric/tf-web-controller
      - tungstenfabric/tf-webui-third-party
    check:
      templates:
        - test-unit-ui
        - ansible-os
        - cleanup
    gate:
      templates:
        - build-ubi
        - build-centos
        - cleanup

- project:
    name: tungstenfabric/tf-ansible-deployer
    check:
      templates:
        - test-tox-pep8
        - test-tox-py36
        - ansible-k8s
        - ansible-os
        - cleanup
    gate:
      templates:
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-kolla-ansible
    check:
      templates:
        - ansible-os
        - cleanup
    gate:
      templates:
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-container-builder
    check:
      templates:
        - ansible-os
        - test-tox-unit
        - cleanup
    gate:
      templates:
        - build-ubi
        - juju-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-vrouter
    check:
      templates:
        - test-unit
        - ansible-os
        - juju-os
        - cleanup
    gate:
      templates:
        - test-unit
        - juju-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-helm-deployer
    check:
      templates:
        - helm-k8s
        - helm-os
        - cleanup
    gate:
      templates:
        - helm-k8s
        - helm-os
        - cleanup

- project:
    name: tungstenfabric/tf-charms
    check:
      streams:
        juju-os-1912:
          voting: false
      templates:
        - test-tox-pep8
        - juju-k8s
        - juju-os
        - juju-os-1912
        - cleanup
    gate:
      templates:
        - juju-k8s
        - juju-os

- project:
    name: tungstenfabric/tf-tripleo-puppet
    check:
      templates:
        - rhosp13
        - rhosp16
        - cleanup
    gate:
      templates:
        - rhosp13
        - rhosp16
        - cleanup

- project:
    name: tungstenfabric/tf-tripleo-heat-templates
    branch: stable/queens
    check:
      templates:
        - rhosp13
        - rhosp13-1912
        - cleanup
    gate:
      templates:
        - rhosp13
        - rhosp13-1912
        - cleanup

- project:
    name: tungstenfabric/tf-tripleo-heat-templates
    branch: stable/train
    check:
      templates:
        - rhosp16
        - cleanup
    gate:
      templates:
        - rhosp16
        - cleanup

- project:
    name: tungstenfabric/tf-operator
    check:
      templates:
        - operator
        - test-unit-go
        - cleanup
    gate:
      templates:
        - operator
        - operator-ha
        - cleanup

- project:
    names:
      - tungstenfabric/tf-vcenter-fabric-manager
      - tungstenfabric/tf-vcenter-manager
    check:
      templates:
        - test-unit
        - build-centos
        - cleanup
    gate:
      templates:
        - test-unit
        - build-centos
        - cleanup

- project:
    name: tungstenfabric/tf-deployment-test
    check:
      templates:
        - test-tox-pep8
        - ansible-os
        - cleanup
    gate:
      templates:
        - build-centos
        - juju-k8s
        - ansible-os
        - cleanup

# infra projects

- project:
    name: tungstenfabric/tf-dev-env
    check:
      templates:
        - build-centos
        - ansible-os
        - cleanup
    gate:
      templates:
        - build-ubi
        - build-centos
        - build-r2011-centos
        - juju-k8s
        - ansible-os
        - cleanup

- project:
    name: baukin/tf-jenkins
    check:
      templates:
        - ansible-os
        - juju-os
        - operator
        - rhosp13
        - rhosp16
        - cleanup

- project:
    name: tungstenfabric/tf-devstack
